# AVELLON VISUAL INTELLIGENCE LIBRARY
# Curated list of cinematic search queries for Pexels API to avoid visual repetition.

IMAGE_PROMPTS = {
    "GEOPOLITICS": [
        "World map with red hotspots highlighting conflict zones",
        "Satellite image of military buildup along a disputed border",
        "Leaders shaking hands at a high-stakes bilateral summit",
        "UN General Assembly hall during a tense voting session",
        "NATO headquarters exterior with member flags",
        "Aircraft carrier strike group sailing in formation",
        "Fighter jets scrambling over contested airspace",
        "Missile launch captured against a dark horizon",
        "Tank columns moving through arid terrain",
        "Naval destroyer escorting merchant vessels",
        "Barbed wire fence along a militarized border",
        "Intelligence analyst studying global maps on screens",
        "Drone surveillance footage over strategic terrain",
        "Special forces boarding operation at sea",
        "Submarine surfacing near polar ice",
        "Defense ministers at a joint press conference",
        "War room situation table with digital global display",
        "Military parade showcasing ballistic missiles",
        "Embassy evacuation scene amid unrest",
        "Refugee columns crossing conflict-affected regions"
    ],
    "MARITIME": [
        "Oil tanker passing through the Strait of Hormuz",
        "Container ships queued at the Suez Canal",
        "Naval patrol boat shadowing a cargo vessel",
        "Map highlighting Malacca Strait trade routes",
        "Pirate skiff approaching commercial shipping lane",
        "LNG carrier docking at a coastal terminal",
        "Port cranes loading containers at dusk",
        "AIS vessel traffic density heatmap",
        "Warship escorting tanker convoy",
        "Blocked canal with stranded mega container ship",
        "Coast guard intercepting suspicious vessel",
        "Offshore drilling platform at sunrise",
        "Maritime exclusion zone graphic overlay",
        "Undersea cable map crossing ocean floors",
        "Naval exercise in disputed waters"
    ],
    "ENERGY": [
        "Brent crude price chart rising sharply on trading screen",
        "Oil pumpjacks silhouetted against sunset",
        "OPEC ministers meeting around conference table",
        "Oil storage tanks viewed from above",
        "Gas pipeline stretching across frozen landscape",
        "Energy traders watching volatile markets",
        "Oil refinery with flaring stacks at night",
        "Tanker unloading crude at port terminal",
        "Global oil supply route map infographic",
        "Strategic petroleum reserve facility entrance",
        "Energy crisis headline superimposed on market chart",
        "Pipeline sabotage aftermath scene",
        "LNG terminal with vapor plumes",
        "Energy minister announcing output cuts",
        "Black gold droplets overlaid on world map"
    ],
    "ECONOMY": [
        "Stock market ticker in red during sell-off",
        "Shipping containers stamped Tariff in bold letters",
        "World Trade Organization headquarters building",
        "Factory floor assembly line halting operations",
        "Inflation graph climbing steeply upward",
        "Currency exchange board flashing volatility",
        "Trade war headline with flags of rival nations",
        "Central bank governor at monetary policy briefing",
        "Cargo ship anchored offshore amid port congestion",
        "Semiconductor chips symbolizing supply chain fragility",
        "Sanctions list document with blacked-out names",
        "Sanctioned oligarch yacht seized in port",
        "Export control announcement press backdrop",
        "Empty supermarket shelves during supply shock",
        "Global supply chain network visualization"
    ],
    "CYBER": [
        "Hacker silhouette against green code matrix",
        "Digital world map with cyberattack vectors highlighted",
        "Ransomware warning message on computer screen",
        "Server racks in dark data center",
        "Lock icon overlaid on binary code",
        "Election interference infographic",
        "Fake news social media feed illustration",
        "Cyber command control center interior",
        "Satellite signal disruption graphic",
        "Critical infrastructure control panel hacked alert",
        "AI neural network visualization",
        "Disinformation bot network diagram",
        "Encrypted communication interface close-up",
        "Cybersecurity team in crisis response mode",
        "Undersea internet cable repair vessel"
    ],
    "CLIMATE": [
        "Melting glacier collapsing into ocean",
        "Wildfire engulfing forested landscape",
        "Flooded city streets after cyclone",
        "Drought-cracked farmland aerial view",
        "Climate protest march in capital city",
        "Hurricane satellite swirl image",
        "Carbon emission stacks emitting smoke",
        "Wind turbines on coastal ridge",
        "Solar farm under vast sky",
        "Climate summit leaders group photo",
        "Heatwave temperature board reading record highs",
        "Desertification spreading across region",
        "Climate migration caravan moving inland",
        "Arctic ice coverage comparison map",
        "Insurance loss chart from climate disasters"
    ],
    "SANCTIONS": [
        "Frozen bank accounts graphic overlay",
        "SWIFT system logo with disconnect headline",
        "Court gavel over international treaty text",
        "Economic blockade naval imagery",
        "Gold reserves vault imagery",
        "Sanctions compliance checklist on desk",
        "Asset seizure headline montage",
        "Diplomatic expulsion airport scene",
        "Trade embargo port closure shot",
        "Sanctioned company headquarters signage"
    ],
    "TECH": [
        "Semiconductor fabrication clean room",
        "Rare earth mining site in rugged terrain",
        "EV battery production line",
        "5G tower installation on city rooftop",
        "Space launch vehicle lifting off",
        "Satellite constellation orbit visualization",
        "Quantum computing processor lab",
        "Strategic minerals shipping containers",
        "Chip export restriction news headline",
        "Robotics replacing factory workers"
    ],
    "INFOGRAPHIC": [
        "World map with arrows showing trade flows",
        "Timeline graphic of escalating conflict",
        "Risk heatmap colored red to green",
        "Barrel price vs geopolitical event overlay",
        "Defense spending comparison bar chart",
        "Maritime chokepoint density map",
        "Global sanctions network web diagram",
        "Currency depreciation comparison chart",
        "Energy dependency matrix between nations",
        "Global Risk Index composite score dashboard visual"
    ]
}
